### ISSUE TITLE
Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by KalleKrasher** [mgibas/EntityFramework.Testing.FakeItEasy#1]
Hi there!
I've used your Aef-class today for some context-faking. But I run into a problem. It would be nice, if you could help me out.

Here's a code-snippet (context has a DbSet of Companies, which have an ID and a name):

```
[Test]
public void TestFakedContextAef()
{
    var context = A.Fake<eftestEntities>();
    var fakeDbSet = Aef.FakeDbSet<Company>();
    A.CallTo(() => context.Companies).Returns(fakeDbSet);

    var company = new Company
    {
        ID = 1,
        Name = "MyCompany"
    };

    context.Companies.Add(company);

    foreach (var comp in context.Companies)
    {
        Console.WriteLine(comp.Name);
    }

    // assert something
}
```

The foreach-loops beaks with an InvalidOperationException: collection was modified; enumeration operation may not execute.

I do not know what to do with the error-message. The application is single-threaded, no removing of company-items, nothing special at all.

Thank you for your support.
Cheers, Kalle

**Comment by mgibas** [comment]
Hi @KalleKrasher - I will take of of that in a short time - sorry for late response.

**Comment by mgibas** [comment]
It took a while but right now it should be working :)
