### ISSUE TITLE
FakeItEasy 2.2.0 support

### ISSUE THREAD

**Issue by nikolay-borzov** [mgibas/EntityFramework.Testing.FakeItEasy#2]
Now it thows `TypeLoadException` exception - Unable to load `FakeItEasy.Creation.IFakeOptionsBuilder` from `FakeItEasy, Version=2.2.0.0`

**Comment by mgibas** [comment]
Now ? Can u provide some example ?

**Comment by nikolay-borzov** [comment]
I have a project targeted to NET. Framework 4.5.2. I use Microsoft Unit Testing Framework

The test method looks like:

```
var users = new List<User>() { ... };
var fakeDbSet = Aef.FakeDbSet(users); // exception on this line
```

Before that in constructor I create fake DbContext.

2 scenarios:
1. I don't have FakeItEasy installed. I install EntityFramework.Testing.FakeItEasy. It installs FakeItEasy  1.25. The test above works.
2. I have FakeItEasy 2.2.0 installed. The test above doesn't work.

If I copy `Aef` class to my project the test works on FakeItEasy 2.2.0

**Comment by mgibas** [comment]
Just bumped all packages so u should be good to go now.
Thanks for that.

**Comment by nikolay-borzov** [comment]
Thanks a lot. I'll try it once I get home

**Comment by nikolay-borzov** [comment]
Verified

**Comment by mgibas** [comment]
thanks
